// app/works/data.ts
import { LoremIpsum } from "lorem-ipsum";

const lorem = new LoremIpsum();

export const works = [
  {
    slug: "lexus-gias",
    name: "GIIAS 2021-2025 ",
    logo: "/images/Client/Lexus.png",
    year: "2025",
    img: "/images/work/lexus/banners.jpg",
    description: "In GIIAS Lexus present its latest in luxury and innovation - featuring new models advanced technology, and warm Omotenashi hospitality, complete with special menu to make every guest feel at home",
    gallery: [
      "/images/work/lexus/1.jpg",
      "/images/work/lexus/2.jpg",
      "/images/work/lexus/3.jpg",
      "/images/work/lexus/4.jpg",
      "/images/work/lexus/6.jpg",
      "/images/work/lexus/7.jpg",
    ],
  },
    {
    slug: "telkomsel-dinner",
    name: "Welcoming Dinner Bali",
    logo: "/images/Client/telkomsel.png",
    year: "2025",
    img: "/images/work/telkomsel/banner.jpg",
    description: "The Welcoming Dinner Bali 2025 was a sophisticated evening hosted by Telkomsel to warmly greet its distinguished guests and partners. Serving as the opening to a larger series of events, the dinner needed to strike a delicate balance between elegance, cultural authenticity, and a seamless guest experience.One of the main challenges was transforming a scenic Bali venue into a space that reflected both Telkomsel’s prestige and the island’s cultural richness, all while accommodating high-profile attendees with diverse expectations. From curating the program flow to orchestrating stage design, fine dining experiences, and local performances, every detail required precision and harmony.Trimar Production brought its expertise to the forefront leveraging years of experience in crafting corporate and luxury events. By combining elegant staging with immersive cultural elements, our team delivered not only a beautiful evening but also a meaningful introduction that set the tone for the days ahead. The result was a welcoming dinner that left guests feeling valued, inspired, and fully engaged from the very start.",
    gallery: [
      "/images/work/telkomsel/1.jpg",
      "/images/work/telkomsel/2.jpg",
      "/images/work/telkomsel/3.jpg",      
      "/images/work/telkomsel/4.jpg",
      "/images/work/telkomsel/5.jpg",
      "/images/work/telkomsel/6.jpg",
    ],
  },
      {
    slug: "asn-kickoff",
    name: "Allianz ASN Kick Off",
    logo: "/images/Client/allianz.png",
    year: "2021",
    img: "/images/work/allianz/banner.jpg",
    description: "Trimar Production transformed Allianz : ASN Kick Off into a groundbreaking virtual experience, adapting to the challenges of the pandemic with creativity and innovation. Instead of a traditional gathering, the event went fully online, yet retained the excitement and energy of a live show. A highlight of the production was the use of interactive projection mapping on dresses, a visual spectacle that elevated the digital stage and kept the audience engaged throughout. Combined with seamless streaming, dynamic presentations, and inspiring content, the event proved that even in a virtual format, a kick-off can be both captivating and memorable.",
    gallery: [
      "/images/work/allianz/1.jpg",
      "/images/work/allianz/2.jpg",
      "/images/work/allianz/3.jpg",      
      "/images/work/allianz/4.jpg",
      "/images/work/allianz/5.jpg",
      "/images/work/allianz/6.jpg",
    ],
  },
    {
    slug: "mandiri-imlek",
    name: "Mandiri Lunar New Year 2573",
    logo: "/images/Client/mandiri.png",
    year: "2022",
    img: "/images/work/mandiri/banner.jpg",
    description: "A festive celebration with elegant Chinese cultural touches, lively performances, and a memorable atmosphere crafted by Trimar Production. Trimar Production successfully organized Mandiri’s Lunar New Year 2573 celebration, transforming the occasion into a vibrant cultural experience. The event embraced the richness of Chinese traditions with elegant décor, festive ambience, and captivating entertainment",
    gallery: [
      "/images/work/mandiri/1.jpg",
      "/images/work/mandiri/2.jpg",
      "/images/work/mandiri/3.jpg",
      "/images/work/mandiri/4.jpg",
      "/images/work/mandiri/5.jpg",
      "/images/work/mandiri/6.jpg",
    ],
  },
      {
    slug: "alibaba",
    name: "Developer Summit 2025",
    logo: "/images/Client/alibaba.png",
    year: "2024",
    img: "/images/work/alibaba/banner.jpg",
    description: "The AI Forward - Alibaba Cloud developer summit 2025 was held on January 21 at Raffles Hotel Jakarta, bringing together 1.200 tech leaders, experts, and developers. The event featured keynotes, product launches, and panels on AI Innovation, along with showcases and networking opportunities centered around Alibaba Cloud Solutions.",
    gallery: [
      "/images/work/alibaba/1.jpg",
      "/images/work/alibaba/2.jpg",
      "/images/work/alibaba/3.jpg",
      "/images/work/alibaba/4.jpg",
      "/images/work/alibaba/5.jpg",
    ],
  },
        {
    slug: "telkomsel-hut29",
    name: "Telkomsel HUT 29th",
    logo: "/images/Client/telkomsel.png",
    year: "2024",
    img: "/images/work/telkomsel/banner2.jpg",
    description: "Trimar Production proudly delivered Telkomsel’s 29th Anniversary Celebration 2024, a grand event that highlighted innovation, connectivity, and appreciation for loyal stakeholders. The 29th Anniversary of Telkomsel in 2024 was more than just a milestone it was a celebration of nearly three decades of innovation, connection, and commitment to empowering Indonesia’s digital society.",
    gallery: [
      "/images/work/telkomsel/11.jpg",
      "/images/work/telkomsel/12.jpg",
      "/images/work/telkomsel/13.jpg",
      "/images/work/telkomsel/14.jpg",
      "/images/work/telkomsel/15.jpg",
      "/images/work/telkomsel/16.jpg",
    ],
  },
      {
    slug: "skk-migas",
    name: "SKK Migas General Affairs Forum",
    logo: "/images/Client/skk.png",
    year: "2018",
    img: "/images/work/skk/banner.jpg",
    description: "Trimar Production proudly executed the SKK Migas – General Affairs Forum 2018 with the theme “Breakthrough Through Synergy”. The event successfully brought together stakeholders in a dynamic and inspiring atmosphere that emphasized collaboration and innovation. Held at a prestigious venue, Trimar Production transformed the forum into an engaging platform where industry leaders and stakeholders could connect, share insights, and build stronger partnerships. Through a thoughtful stage design, impactful visuals, and seamless event flow, we ensured that the core message of synergy was not only delivered but also experienced by every participant. The event reflected the spirit of SKK Migas in driving breakthroughs through collective effort and innovation. At Trimar Production, we take pride in curating corporate events that go beyond formality, elevating them into experiences that inspire, connect, and leave a lasting impact. The General Affairs Forum 2018 is one of many milestones that showcase our commitment to excellence in event execution.",
    gallery: [
      "/images/work/skk/1.jpg",
      "/images/work/skk/2.jpg",
      "/images/work/skk/3.jpg",
    ],
  },
      {
    slug: "manulife",
    name: "Manulife ACC",
    logo: "/images/Client/manulife.png",
    year: "2024",
    img: "/images/work/manulife/banner.jpg",
    description: "Trimar Production had the honor of organizing Manulife ACC 2024 – Mahakarya Sang Bintang, Agency Award Celebration. This prestigious event was dedicated to celebrating the outstanding achievements of Manulife’s top-performing agencies, bringing together recognition, inspiration, and unforgettable moments. With a concept that highlighted brilliance and excellence, the celebration featured spectacular stage design, world-class entertainment, and a seamless flow of program that reflected Manulife’s spirit of growth and recognition. Every detail was carefully crafted to create an atmosphere of pride and inspiration, leaving a lasting impact on all attendees. For Trimar Production, delivering Mahakarya Sang Bintang was not just about producing an event, but about creating a masterpiece of celebration honoring success and motivating future achievements.",
    gallery: [
      "/images/work/manulife/1.jpg",
      "/images/work/manulife/2.jpg",
      "/images/work/manulife/3.jpg",
    ],
  },
        {
    slug: "generali-mega",
    name: "Generali Mega Seminar",
    logo: "/images/Client/generali.png",
    year: "2024",
    img: "/images/work/generali/banner.jpg",
    description: "Trimar Production delivered the Generali Mega Seminar 2024, an inspiring corporate gathering designed to empower and energize participants with impactful content and seamless execution The Generali Mega Seminar 2024 was a milestone event designed to bring together Generali’s top leaders, partners, and professionals in an atmosphere of inspiration and collaboration. With a strong focus on knowledge sharing, motivation, and strategic alignment, the seminar created a platform where participants could engage with new ideas and strengthen their commitment to Generali’s vision for the future. For Trimar Production, the Generali Mega Seminar 2024 was more than just an event, it was an opportunity to empower participants, strengthen corporate spirit, and celebrate Generali’s drive for excellence.",
    gallery: [
      "/images/work/generali/1.jpg",
      "/images/work/generali/2.jpg",
      "/images/work/generali/3.jpg",
    ],
  },
  // {
  //   slug: "lexus-feast",
  //   name: "Lexus Feast",
  //   logo: "/images/Client/Lexus.png",
  //   year: "2024",
  //   img: "/images/work/lexus/banner2.jpg",
  //   description: "Trimar Production proudly presented Lexus Feast, an exclusive dining experience that combined luxury, innovation, and sustainability. Hosted at Immersion by Lexus, the event featured curated menus, refined entertainment, and a showcase of Lexus’ latest models in collaboration with top fine dining restaurants. The refined entertainment and atmosphere created a seamless balance between sophistication and innovation, offering guests a memorable multi-sensory experience. Complementing the dining journey, the latest Lexus models were showcased, allowing guests to engage with the brand’s vision of sustainable luxury and cutting edge technology. Through Lexus Feast, Trimar Production elevated the traditional fine dining event into an exclusive brand experience that celebrated not only gastronomy but also the Lexus lifestyle of innovation, refinement, and conscious luxury.",
  //   gallery: [
  //     "/images/work/lexus/11.jpg",
  //     "/images/work/lexus/banner2.jpg",
  //     "/images/work/lexus/5.jpg",
  //   ],
  // },
  {
    slug: "dipo-star",
    name: "Dipo Star Finance 2018",
    logo: "/images/Client/dipo.webp",
    year: "2018",
    img: "/images/work/dipo/banner.jpg",
    description: "Trimar Production successfully organized the Finance Marketing Conference 2018 for Dipo Star Finance, creating a professional platform that emphasized innovation, strategy, and future growth in the finance industry. This conference not only facilitated discussions on financial marketing excellence but also empowered participants with insights and strategies to drive growth in a competitive market. For Trimar Production, it was a privilege to craft an event that contributed to the advancement of the finance industry.",
    gallery: [
      "/images/work/dipo/1.jpg",
      "/images/work/dipo/2.jpg",
      "/images/work/dipo/3.jpg",
    ],
  },

    {
    slug: "mandiri-raker",
    name: "Mandiri Raker",
    logo: "/images/Client/mandiri.png",
    year: "2022",
    img: "/images/work/mandiri/banner2.jpg",
    description: "Perform & Transform Be Global Be Digital 2022 / Rapat Kerja Corporate Banking 2022. Trimar Production organized Mandiri’s annual Raker 2022 with the theme “Perform & Transform: Be Global Be Digital.” The event was designed to reflect Mandiri’s vision of transformation through modern stage design, seamless program execution, and impactful multimedia presentations. It became an inspiring platform that energized participants to embrace innovation and excellence, leaving a lasting impression on all attendees.",
    gallery: [
      "/images/work/mandiri/11.jpg",
      "/images/work/mandiri/12.jpg",
      "/images/work/mandiri/13.jpg",
    ],
  },
    {
    slug: "jafra",
    name: "The Jafra AAC 2022",
    logo: "/images/Client/jafra.png",
    year: "2022",
    img: "/images/work/jafra/banner.jpg",
    description: "A prestigious celebration by Trimar Production, honoring top agents while unveiling new products and innovations in an inspiring atmosphere. Trimar Production proudly organized The Jafra AAC 2022, a distinguished event that not only celebrated the remarkable achievements of Jafra’s top agents but also became the stage for launching exciting new products and initiatives. With an inspiring program flow, impactful stage design, and engaging entertainment, the event highlighted Jafra’s commitment to innovation and recognition. It was more than a celebration, it was a milestone moment that honored excellence, energized the community, and marked a new chapter in Jafra’s journey.",
    gallery: [
      "/images/work/jafra/1.jpg",
      "/images/work/jafra/2.jpg",
    ],
  },
      {
    slug: "manulife-malay",
    name: "Manulife Malaysia",
    logo: "/images/Client/manulife.png",
    year: "2024",
    img: "/images/work/manulife/banner2.jpg",
    description: "Trimar Production delivered an elegant and inspiring award night in Kuala Lumpur, celebrating achievement with grand performances and immersive stage design On January 13, 2024, Trimar Production proudly organized Manulife Malaysia: Symphony of Glory in Kuala Lumpur, a prestigious celebration honoring excellence and achievement. Designed as a symphony of culture, performance, and elegance, the event brought together inspiring award moments, captivating stage presentations, and a sophisticated atmosphere.", 
    gallery: [
      "/images/work/manulife/11.jpg",
      "/images/work/manulife/12.jpg",
      "/images/work/manulife/13.jpg",
    ],
  },
        {
    slug: "omdc",
    name: "OMDC 10th Anniversary",
    logo: "/images/Client/omdc.png",
    year: "2023",
    img: "/images/work/omdc/banner.jpg",
    description: "", 
    gallery: [
      "/images/work/omdc/1.jpg",
      "/images/work/omdc/2.jpg",
    ],
  },
  {
    slug: "tsel-bestcs",
    name: "Telkomsel Best CS 2015-2017",
    logo: "/images/Client/telkomsel.png",
    year: "2017",
    img: "/images/work/telkomsel/banner3.jpg",
    description: "Telkomsel Best CS, organized by Trimar Production, was a special recognition event celebrating the dedication and achievements of Telkomsel’s top customer service talents. With an inspiring awards ceremony, engaging performances, and a lively atmosphere, the event honored those who consistently deliver excellence, while fostering pride and motivation among all participants.", 
    gallery: [
      "/images/work/telkomsel/21.jpg",
      "/images/work/telkomsel/22.jpg",
      "/images/work/telkomsel/23.jpg",
    ],
  },
    {
    slug: "tsel-tiktok",
    name: "Press Launch Simpati X Tiktok",
    logo: "/images/Client/telkomsel.png",
    year: "2025",
    img: "/images/work/telkomsel/banner4.jpg",
    description: "Telkomsel Best CS, organized by Trimar Production, was a special recognition event celebrating the dedication and achievements of Telkomsel’s top customer service talents. With an inspiring awards ceremony, engaging performances, and a lively atmosphere, the event honored those who consistently deliver excellence, while fostering pride and motivation among all participants.", 
    gallery: [
      "/images/work/telkomsel/41.jpg",
      "/images/work/telkomsel/42.jpg",
    ],
  },
      {
    slug: "tsel-ecommerce",
    name: "Telkomsel eCommerce Summit",
    logo: "/images/Client/telkomsel.png",
    year: "2016",
    img: "/images/work/telkomsel/banner5.jpg",
    description: "Telkomsel E-Commerce 2016, executed by Trimar Production, was a dynamic forum that brought together industry leaders, partners, and innovators to explore the future of digital commerce. Featuring insightful presentations, interactive discussions, and engaging event design, the program highlighted Telkomsel’s commitment to driving growth and innovation in Indonesia’s digital ecosystem.", 
    gallery: [
      "/images/work/telkomsel/51.jpg",
      "/images/work/telkomsel/52.jpg",
      "/images/work/telkomsel/53.jpg",
    ],
  },
        {
    slug: "generali-premiere-2015",
    name: "Generali Premier Award 2015",
    logo: "/images/Client/generali.png",
    year: "2015",
    img: "/images/work/generali/banner2.jpg",
    description: "Trimar Production proudly executed the Generali Premier Award 2015, a prestigious recognition night honoring top achievers with an elegant and inspiring celebration. The Generali Premier Award 2015 was a night of prestige and recognition, dedicated to celebrating the outstanding achievements of Generali’s top performers. Held in an atmosphere of elegance and exclusivity, the event was designed to reflect Generali’s values of excellence, commitment, and innovation. Trimar Production curated every detail, from stage design and visual storytelling to program flow and entertainment, to elevate the celebration into a truly memorable experience. This award ceremony went beyond acknowledging achievements; it served as a source of motivation and inspiration for the entire Generali community. Through creativity and seamless execution, Trimar Production ensured that the Premier Award 2015 stood as a milestone event that honored success while encouraging continued growth.",
    gallery: [
      "/images/work/generali/11.jpg",
      "/images/work/generali/12.jpg",
      "/images/work/generali/13.jpg",
    ],
  },
          {
    slug: "generali-premiere-2019",
    name: "Generali Premier Award 2019",
    logo: "/images/Client/generali.png",
    year: "2019",
    img: "/images/work/generali/banner3.jpg",
    description: "Trimar Production proudly presented the Generali Premier Award 2019, an elegant evening dedicated to recognizing the outstanding achievements of Generali’s top performers. The Generali Premier Award 2019 was a prestigious celebration honoring Generali’s finest achievers, designed to inspire excellence and reinforce the spirit of success. With a refined concept and elegant stage design, Trimar Production transformed the award ceremony into an unforgettable night of recognition. Every detail from the thematic visuals to the curated entertainment, was crafted to reflect Generali’s commitment to innovation, dedication, and outstanding performance. More than just an award ceremony, the event embodied Generali’s vision of celebrating success while motivating its people to reach even greater heights. For Trimar Production, it was an honor to elevate the Premier Award 2019 into a remarkable experience that left a lasting impression on all attendees.",
    gallery: [
      "/images/work/generali/21.jpg",
      "/images/work/generali/22.jpg",
      "/images/work/generali/23.jpg",
    ],
  },
          {
    slug: "generali-premiere-2023",
    name: "Generali Premier Award 2023",
    logo: "/images/Client/generali.png",
    year: "2023",
    img: "/images/work/generali/banner4.jpg",
    description: "Trimar Production delivered the Generali Premier Award 2023, a prestigious recognition night honoring Generali’s top achievers with an elevated blend of elegance, innovation, and inspiration. The Generali Premier Award 2023 stood as a remarkable evening where Generali celebrated the extraordinary performance and dedication of its top achievers. With a concept designed to merge prestige and innovation, Trimar Production curated every detail of the event from immersive stage design, lighting, and thematic storytelling, to refined entertainment that elevated the atmosphere of recognition and celebration. This award ceremony was more than just an acknowledgment of excellence; it was a powerful showcase of Generali’s vision to inspire, empower, and set new standards for achievement. For Trimar Production, being entrusted with the Premier Award 2023 was an honor, and we ensured the event became not only a celebration of success but also a memorable milestone for all who attended.",
    gallery: [
      "/images/work/generali/31.jpg",
      "/images/work/generali/32.jpg",
      "/images/work/generali/33.jpg",
    ],
  },
            {
    slug: "club-recog-2017",
    name: "Club Recognition 2017-2018",
    logo: "/images/Client/allianz.png",
    year: "2023",
    img: "/images/work/allianz/banner2.jpg",
    description: "A prestigious celebration by Allianz that honors top-performing agents for their dedication, excellence, and remarkable achievements throughout the year. Allianz held the ASN Club Recognition in Indonesia to celebrate and acknowledge the outstanding achievements of its top-performing agents. This prestigious gathering served not only as an awards ceremony but also as a platform to honor the agents’ dedication, resilience, and excellence in driving success throughout the year.",
    gallery: [
      "/images/work/allianz/11.jpg",
      "/images/work/allianz/12.jpg",
      "/images/work/allianz/13.jpg",
    ],
  },
      {
    slug: "telkomsel-agent-2017",
    name: "Telkomsel Agent of Change 2017",
    logo: "/images/Client/telkomsel.png",
    year: "2017",
    img: "/images/work/telkomsel/banner6.jpg",
    description: "Telkomsel Agent Change, produced by Trimar Production, addressed the challenge of guiding frontliners through a time of transformation. By creating an engaging event concept that combined motivational content, interactive workshops, and inspiring stage experiences, Trimar provided a seamless solution that not only energized participants but also equipped them to embrace change with confidence and unity.",
    gallery: [
      "/images/work/telkomsel/61.jpg",
      "/images/work/telkomsel/62.jpg",
      "/images/work/telkomsel/63.jpg",
    ],
  },
      {
    slug: "telkomsel-jalin-nusa",
    name: "Telkomsel Jalin Nusa",
    logo: "/images/Client/telkomsel.png",
    year: "2024",
    img: "/images/work/telkomsel/banner7.jpg",
    description: "Telkomsel Jalin Nusa 2024, organized by Trimar Production, was a nationwide gathering that celebrated connection, collaboration, and digital innovation. Through inspiring sessions, cultural showcases, and engaging activities, the event strengthened Telkomsel’s bond with communities across Indonesia, highlighting its commitment to uniting the nation through technology and meaningful experiences.",
    gallery: [
      "/images/work/telkomsel/71.jpg",
      "/images/work/telkomsel/72.jpg",
      "/images/work/telkomsel/73.jpg",
    ],
  },
      {
    slug: "telkomsel-tew-Singtel",
    name: "Telkomsel Tew Singtel",
    logo: "/images/Client/telkomsel.png",
    year: "2024",
    img: "/images/work/telkomsel/banner9.jpg",
    description: "As part of the regional collaboration, Tew Singtel 2024 brought together Telkomsel and Singtel leadership in a high-level forum. Trimar Production crafted a professional yet engaging setting that enabled knowledge exchange, innovation sharing, and reinforced the partnership between the two telecommunications giants.",
    gallery: [
      "/images/work/telkomsel/91.jpg",
      "/images/work/telkomsel/92.jpg",
      "/images/work/telkomsel/93.jpg",
    ],
  },
];
